apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    app: cache
  ports:
    - port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  labels:
    app: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      containers:
      - name: api
        image: nicholasjackson/fake-service:v0.23.1
        ports:
          - containerPort: 9092
        env:
        - name: 'LISTEN_ADDR'
          value: '127.0.0.1:9092'
        - name: 'NAME'
          value: 'cache'
        - name: 'MESSAGE'
          value: 'Cache Response'
        - name: TRACING_ZIPKIN
          value: http://simplest-collector-headless.observability:9411
      - args:
        - --reporter.grpc.host-port=dns:///simplest-collector-headless.observability:14250
        - --reporter.type=grpc
        image: jaegertracing/jaeger-agent:latest
        imagePullPolicy: IfNotPresent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 5778
          name: config-rest
          protocol: TCP
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 14271
          name: admin-http
          protocol: TCP