apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-na
---
apiVersion: v1
kind: Service
metadata:
  name: web-na
spec:
  selector:
    app: web-na
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy-na
  labels:
    app: web-na
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-na
  template:
    metadata:
      labels:
        app: web-na
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'api.default.default:9091'
    spec:
      serviceAccountName: web-na
      containers:
        - name: web-na
          image: nicholasjackson/fake-service:v0.23.1
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            - name: 'UPSTREAM_URIS'
              value: 'http://localhost:9091'
            - name: 'NAME'
              value: 'web-na'
            - name: 'MESSAGE'
              value: 'Hello World'